
# Update these with your Supabase details from your project settings > API
project_id = "yajulpyjxgwehomkqdqv"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[experimental]
enabled = false

[[functions]]
name = "send-contact-email"
verify_jwt = false

[[functions]]
name = "send-address-request-notification"
verify_jwt = false

[[functions]]
name = "health-check"
verify_jwt = false

[[functions]]
name = "create-user"
verify_jwt = true
