// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yajulpyjxgwehomkqdqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhanVscHlqeGd3ZWhvbWtxZHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5ODE4ODQsImV4cCI6MjA1ODU1Nzg4NH0.LMqC7cMfDnAyEJmF_NyVwxSt8A-e17qxCLyipVRs4ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);